"""add tsunami_risk_zones table

Revision ID: 82d3b0cda531
Revises: 984bf9d448d0
Create Date: 2026-07-21 11:18:06.017812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d3b0cda531'
down_revision: Union[str, Sequence[str], None] = '984bf9d448d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tsunami_risk_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('low_elevation_fraction', sa.Float(), nullable=False),
    sa.Column('mean_elevation_m', sa.Float(), nullable=False),
    sa.Column('distance_to_1945_epicenter_km', sa.Float(), nullable=False),
    sa.Column('methodology_note', sa.String(length=500), nullable=False),
    sa.Column('computed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tsunami_risk_zones')
    # ### end Alembic commands ###
